### ISSUE TITLE
externalCheckout.cmsUrl in README.md wrong?

### ISSUE THREAD

**Issue by phoenixdev-kl** [Vendic/vsf-external-checkout#9]
I've installed the module as described in README.md, but when clicking the checkout button, I get redirected to an URL like https://yourcmsaddress.com?token=&cart=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYXJ0SWQiOiIxNTc5In0.hMe8x_0U1GwRMwMMIJfGHzrAGx0PawIdZbC9tReiZoM, but what I understand from the documentation is, that it should actually redirect to https://yourcmsaddress.com/vue/cart/sync?token=&cart=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYXJ0SWQiOiIxNTc5In0.hMe8x_0U1GwRMwMMIJfGHzrAGx0PawIdZbC9tReiZoM and therefore the value for externalCheckout.cmsUrl in local.json should be **https://yourcmsaddress.com/vue/cart/sync**. Is that correct or did I screwed something else up?

See https://github.com/Vendic/vsf-external-checkout/blame/ecd5653fadf90f04cbb03a0bc399add59355129b/README.md#L29

**Comment by Tjitse-E** [comment]
@phoenixdev-kl the cms url should be just 'https://yourcmsaddress.com'. Could you try the new release [1.1.1](https://github.com/Vendic/vsf-external-checkout/releases/tag/1.1.1)?

In a moment i'll also release v2.0.0 that's only compatible with VueStorefront 1.9, [because of](https://docs.vuestorefront.io/guide/upgrade-notes/):
> @vue-storefront/store package has been depreciated. Just change imports to @vue-storefront/core/store.

So make sure you download the right release.

**Comment by phoenixdev-kl** [comment]
Thanks @Tjitse-E! Works like a charm with version 1.1.1 and just https://yourcmsaddress.com 👍
Made my day! 🥇

**Comment by Tjitse-E** [comment]
Great!
